### ISSUE TITLE
Need prefix for functions

### ISSUE THREAD

**Issue by martin9700** [AtlassianPS/BitbucketPS#19]
I know this was just removed, but it's badly needed.  Jira is already using a prefix (Jira), but this module and the Confluence module are already in conflict.  Both use Invoke-Method.  

I propose we go back to BB, or BitB or something to differentiate this module from others.

**Comment by lipkau** [comment]
Why should they be in conflict?
They are private methods....

also, the module has a prefix: `BitBucket` (by default. which can be changed with `Import-Module BitBucketPS -Prefix BB`

**Comment by martin9700** [comment]
> Why should they be in conflict?  They are private methods....

That are loaded into memory.  If I Invoke-Method how does PowerShell know which to use?  

> also, the module has a prefix: BitBucket

Where?  I don't see anything in the manifest

> (by default. which can be changed with Import-Module BitBucketPS -Prefix BB

I don't think pushing the responsibility of conflict resolution onto the user is the right answer.  Especially when you're talking about a products within the same company.    If you conflict with some other random module, oh well you can only control so much.  But we can control this and make the experience seamless.  Why NOT do it?

**Comment by martin9700** [comment]
Ok, found the prefix.  Was looking at the wrong repo (ironically, my own!)

Haven't played with that much.  Is the idea to allow you to use the same functions in multiple modules?

**Comment by lipkau** [comment]
> That are loaded into memory. If I Invoke-Method how does PowerShell know which to use?

Private methods only exist in the context of the module. so only functions of the module have access to it. it doesn't exist outside the module.

> Is the idea to allow you to use the same functions in multiple modules?

No. The idea of the `-Prefix` is that the default might be too long (or otherwise unwanted) for the user. So he gets the chance to change it to what he prefers; but the verb and the noun (without prefix) are unchanged
