### ISSUE TITLE
Question about Convertfrom-Json2

### ISSUE THREAD

**Issue by martin9700** [AtlassianPS/BitbucketPS#3]
I was curious why you are using convertfrom-json2 instead of the built in convertfrom-json?  In my testing of the module I cannot find a difference but maybe I'm missing something?

Thanks!

**Comment by lipkau** [comment]
This is where the function was introduced along with the explanation:

https://github.com/AtlassianPS/JiraPS/pull/23

**Comment by martin9700** [comment]
Great, I have updated in pull request #5
