### ISSUE TITLE
Rest API version reference

### ISSUE THREAD

**Issue by martin9700** [AtlassianPS/BitbucketPS#4]
I noticed in some examples in the API documentation that instead of using:

`/rest/api/1.0/`

this was used instead:

`/rest/api/latest/`

Is there any reason the latter shouldn't be used?  Realistically will the URL ever change from 1.0?

**Comment by lipkau** [comment]
Yes. `latest` is used for a reason:

The API might be change and will therefore get a new version. Confluence and Jira are on version 2.0.

`latest` is a symbolic link created by the server to the latest version.

**Comment by lipkau** [comment]
Yes. `latest` is used for a reason:

The API might be change and will therefore get a new version. Confluence and Jira are on version 2.0.

`latest` is a symbolic link created by the server to the latest version.

**Comment by martin9700** [comment]
That was my thought and that's what I went with in PR #5
